services:
    anime_db.ani_db.browser.client.guzzle:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\Client\GuzzleClient
        arguments:
            - '@anime_db.ani_db.browser.client.guzzle.guzzle'
            - '@anime_db.ani_db.browser.client.guzzle.request_configurator'
            - '@anime_db.ani_db.browser.response_repair'
            - '%anime_db.ani_db.api.prefix%'
        public: false

    anime_db.ani_db.browser.client.guzzle.guzzle:
        class: GuzzleHttp\Client
        arguments:
            base_uri: '%anime_db.ani_db.api.host%'
        public: false

    anime_db.ani_db.browser.client.guzzle.request_configurator:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\Client\Guzzle\RequestConfigurator
        calls:
            - [setProtocolVersion, ['%anime_db.ani_db.api.protover%']]
            # TODO need set from DI configurator
            - [setAppCode, ['%anime_db.ani_db.app_code%']]
            - [setAppClient, ['%anime_db.ani_db.app_client%']]
            - [setAppVersion, ['%anime_db.ani_db.app_version%']]
        public: false

    anime_db.ani_db.browser.response_repair:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Util\ResponseRepair
        public: false
