services:
    anime_db.ani_db.browser.client.guzzle:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\Client\GuzzleClient
        arguments:
            - '@anime_db.ani_db.browser.client.guzzle.guzzle'
            - '@anime_db.ani_db.browser.response_repair'
            - '%anime_db.ani_db.api.prefix%'
            - '%anime_db.ani_db.api.client%'
            - '%anime_db.ani_db.api.clientver%'
            - '%anime_db.ani_db.api.protover%'
            - '%anime_db.ani_db.app_code%'
        public: false

    anime_db.ani_db.browser.client.guzzle.guzzle:
        class: Guzzle\Http\Client
        arguments: [ '%anime_db.ani_db.api.host%' ]
        public: false

    anime_db.ani_db.browser.response_repair:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Util\ResponseRepair
        public: false
