services:
    anime_db.shikimori.browser:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\Browser
        arguments:
            - %anime_db.shikimori.host%
            - %anime_db.shikimori.api.host%
            - %anime_db.shikimori.api.prefix%
            - %anime_db.shikimori.api.client%
            - %anime_db.shikimori.api.clientver%
            - %anime_db.shikimori.api.protover%