parameters:
    anime_db.ani_db.host: 'http://anidb.net'
    anime_db.ani_db.api.host: 'http://api.anidb.net:9001'
    anime_db.ani_db.api.prefix: '/httpapi'
    anime_db.ani_db.api.protover: 1

    # TODO need set from DI configurator
    anime_db.ani_db.app_client: 'animedbplugin'
    anime_db.ani_db.app_version: 2
    anime_db.ani_db.app_code: 'api-team-8069EC4798E98A3BC14382D9DAA2498C'

    anime_db.ani_db.image_prefix: 'http://img7.anidb.net/pics/anime/'
    anime_db.ani_db.cache.dir: '%kernel.cache_dir%/ani_db_response/'
    anime_db.ani_db.cache.requests:
        anime: '+1 week'
        categorylist: '+6 month'
        randomrecommendation: ~
        randomsimilar: ~
        mylistsummary: ~
        hotanime: '+1 day'
        main: '+1 day'
