services:
    anime_db.ani_db.browser:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\Browser
        arguments:
            - @anime_db.shikimori.browser.client
            - %anime_db.ani_db.host%
            - %anime_db.ani_db.api.prefix%
            - %anime_db.ani_db.api.client%
            - %anime_db.ani_db.api.clientver%
            - %anime_db.ani_db.api.protover%
            - %anime_db.ani_db.image_prefix%

    anime_db.ani_db.browser.client:
        class: Guzzle\Http\Client
        arguments: [ %anime_db.ani_db.api.host% ]
        calls:
            - [ setDefaultHeaders, [ ["User-Agent": %anime_db.ani_db.app_code%] ] ]
        public: false

    anime_db.ani_db.browser.cache:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\CacheResponse
        arguments: [ %anime_db.ani_db.cache_response_dir% ]
        public: false