imports:
    - { resource: 'services/guzzle_client.yml' }
    - { resource: 'services/cache_client.yml' }

services:
    anime_db.ani_db.browser:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\Browser
        arguments:
            - '@anime_db.ani_db.browser.client.guzzle.guzzle'
            - '@anime_db.ani_db.browser.response_repair'
            - '%anime_db.ani_db.host%'
            - '%anime_db.ani_db.api.prefix%'
            - '%anime_db.ani_db.api.client%'
            - '%anime_db.ani_db.api.clientver%'
            - '%anime_db.ani_db.api.protover%'
            - '%anime_db.ani_db.app_code%'
            - '%anime_db.ani_db.image_prefix%'
        calls:
            - [ setResponseCache, [ '@anime_db.ani_db.browser.cache' ] ]

    # deprecated
    anime_db.ani_db.browser.cache:
        class: AnimeDb\Bundle\AniDbBrowserBundle\Service\CacheResponse
        arguments:
            - '@filesystem'
            - '@anime_db.ani_db.browser.client.cache.expire_resolver'
            - '%anime_db.ani_db.cache_response_dir%'
        public: false
